sudo: false
language: node_js
node_js:
  - 6
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm i karma-phantomjs-launcher
after_success:
  - cat ./coverage/report-lcov/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
cache:
  directories:
    - node_modules
